### ISSUE TITLE
Variables renaming

### ISSUE THREAD

**Issue by kiwina** [1egoman/debundle#11]
hi i noticed that in webpack a lot of variables get renamed to module, exports, require any way around that?
Also on windows debundler fails at getModuleLocation when it checks if (!filePath.startsWith(pathPrefix)) 
removing the check gets the output

**Comment by 1egoman** [comment]
> i noticed that in webpack a lot of variables get renamed to module, exports, require any way around that?

Not with this package. You could potentially preprocess the bundle somehow?

> Also on windows debundler fails at getModuleLocation when it checks if (!filePath.startsWith(pathPrefix)) removing the check gets the output.

Ok. Can you give me a more thorough example? I can't help you if you don't give me details.

**Comment by kiwina** [comment]
getModuleLocation error happens with any of the tests on windows

**Comment by 1egoman** [comment]
Ah ok, take a look at https://github.com/1egoman/debundle/blob/master/DOCS.md#replacerequires, which might help clarify (a bit) what's going on.

**Comment by 1egoman** [comment]
Closed due to inactivtiy
